name: workflow
on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say hello
        run: |
          echo "Hello world!"
          echo "This is GitHub Actions doing its thing 🤖"
      - name: Print current date and time
        run: date
      - name: List files in repo
        run: ls -l
      - name: Random fun message
        run: echo "Today is a great day to automate stuff! 🎉"

  check-environment:
    needs: say-hello
    runs-on: ubuntu-latest
    steps:
      - name: Show system info
        run: uname -a
      - name: Check disk space
        run: df -h
      - name: Print environment variables
        run: env

  get-weather:
    needs: say-hello
    runs-on: ubuntu-latest
    steps:
      - name: Fetch weather for Bengaluru
        run: |
          curl "https://api.open-meteo.com/v1/forecast?latitude=12.9716&longitude=77.5946&current_weather=true" -o weather.json
          cat weather.json




